spring:
  application:
    name: hotelbooking
  output:
    ansi:
      enabled: ALWAYS
  profiles:
    group:
      local-in-memory:
        - booking-in-memory
        - inventory-in-memory
        - demo-in-memory
      local-mongo:
        - booking-in-memory
        - inventory-mongo
      local-postgres-mongo:
        - booking-postgres
        - inventory-mongo