spring:
  application:
    name: inventory-service
  output:
    ansi:
      enabled: ALWAYS
  profiles:
    group:
      local:
        - inventory-mongo
        - inventory-grpc-server
        - security-dev
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/hotelbooking}

server:
  port: 8081

inventory:
  grpc:
    server:
      port: 9090
      tls:
        enabled: ${INVENTORY_GRPC_SERVER_TLS_ENABLED:true}
        certificate-chain: ${INVENTORY_GRPC_SERVER_CERTIFICATE_CHAIN:certs/dev/inventory-service.crt}
        private-key: ${INVENTORY_GRPC_SERVER_PRIVATE_KEY:certs/dev/inventory-service.key}
        trust-cert-collection: ${INVENTORY_GRPC_TRUST_CERT_COLLECTION:certs/dev/ca.crt}
      mtls:
        allowed-client-common-name: ${INVENTORY_GRPC_ALLOWED_CLIENT_COMMON_NAME:booking-service}